### ISSUE TITLE
Send with async flag not behaving as expected

### ISSUE THREAD

**Issue by anirvan-majumdar** [rschreijer/lutung#17]
The `MandrillApi` class' send message accepts a `async` flag. However, even if I pass in `true` for it, the execution thread waits for the mails to be dispatched. Setting the flag to `false` behaves the same as well.

Is there some other settings required to be made for dispatching the mails in an asynchronous manner?

**Comment by alemhnan** [comment]
I'm having the same problem. No matter the value of async the result will be 'sent' with a blocking request.

I've tried using the [curl](https://mandrillapp.com/api/docs/messages.curl.html) version of the apis and it is actually giving me a "queued" as status. But again it doesn't matter what you put as async value. 
I've opened a ticket in Mandrill. I will write you back when I will hear from them.
