### ISSUE TITLE
Template Vars

### ISSUE THREAD

**Issue by xritchie** [rschreijer/lutung#36]
Hi

Does the library support local variables for Mandrill Templates

example

```
"global_merge_vars": [
            {
                "name": "merge1",
                "content": "merge1 content"
            }
        ],
        "merge_vars": [
            {
                "rcpt": "recipient.email@example.com",
                "vars": [
                    {
                        "name": "merge2",
                        "content": "merge2 content"
                    }
                ]
            }
        ],
```

**Comment by n0mer** [comment]
@xritchie where did you found it? :)

**Comment by billoneil** [comment]
@n0mer Does the API still work since Mandrill was moved into MailChimp? I figured it would be a different API.

**Comment by billoneil** [comment]
https://github.com/rschreijer/lutung/blob/04883e0e366caf373a48e7ba74eae2d514fa873a/src/main/java/com/microtripit/mandrillapp/lutung/view/MandrillMessage.java#L425
