### ISSUE TITLE
Metadata from /messages/search.json not mapped

### ISSUE THREAD

**Issue by rschreijer** [rschreijer/lutung#4]
The metadata returned by the mandrill api on /messages/search.json does not get mapped to a member of MandrillMessageInfo

**Comment by joseanibl138** [comment]
It can be re-enabled. I have done so and it works without issues. The only extra step needed is in the Mandrill account itself @ Mandrill.com website. The particular metadata fields that you want to use and search by, must be created/configured for the search to return results.

**Comment by billoneil** [comment]
https://github.com/rschreijer/lutung/commit/3ad452da8fe98513ff93b325f4ed09158ed4313a
