### ISSUE TITLE
async send generates android.os.NetworkOnMainThreadException

### ISSUE THREAD

**Issue by mcyrulik** [rschreijer/lutung#52]
I'm using 

mandrillApi.messages().send(message, true);

This is generating an Exception on android:  android.os.NetworkOnMainThreadException in android 5.0.0 API 21.

.send(message, false) produces the same Exception.

**Comment by uditmukherjee** [comment]
You should be doing that in an AsyncTask (essentially in a different thread but not on the main thread)

**Comment by AmirHadifar** [comment]
@uditmukherjee can you please give me some piece of code ? Thanks :)

**Comment by AmirHadifar** [comment]
@mcyrulik Did you find any solution ?

**Comment by mcyrulik** [comment]
@AmirHadifar  Nope, I ended up writing my own Class that extended AsyncTask to send the emails with a HttpsURLConnection.

**Comment by AmirHadifar** [comment]
@mcyrulik Could you please post your code here to see what you do ? I really need this :(

**Comment by rschreijer** [comment]
```mandrillApi.messages().send(message, true);``` doesn't mean that the call to mandrills API is made async, it only tells mandrills API to respond right away rather then actually waiting for the emails to be sent. The API call however is made on the same thread. Lutung does not use any subthreads or such.

In Android, one should never do such things on the main thread. Move executing mandrill calls to a different thread!
