### ISSUE TITLE
java.lang.NoSuchMethodError in RequestDispatcher

### ISSUE THREAD

**Issue by mcyrulik** [rschreijer/lutung#53]
Using the send() method, I get an exception when sending any message:

java.lang.NoSuchMethodError: No static method consume(Lorg/apache/http/HttpEntity;)V in class Lorg/apache/http/util/EntityUtils; or its super classes (declaration of 'org.apache.http.util.EntityUtils' appears in /system/framework/ext.jar) at com.microtripit.mandrillapp.lutung.model.MandrillRequestDispatcher.execute(MandrillRequestDispatcher.java:104)

**Comment by irufus** [comment]
Are you using maven to pull down your dependencies?

**Comment by mcyrulik** [comment]
Using gradle in android studio:

    compile 'com.mandrillapp.wrapper.lutung:lutung:0.0.5'

The email actually still sends, but then the app crashes.

**Comment by irufus** [comment]
What version of httpclient are you using?

**Comment by anilgooru** [comment]
Hi irufus,

I too get same issue. I am using j2ee application.

Thanks,
Anil.

**Comment by kibotu** [comment]
same sadly

**Comment by kllaas** [comment]
Hi, I got same problem and I wrote about this on the StackOverFlow. Please, help me.
http://stackoverflow.com/questions/31817947/java-lang-nosuchmethoderror-when-trying-to-use-madrill-in-android-app

**Comment by kibotu** [comment]
I ended up using a different lib: https://github.com/littleli/mandrill-tiny since i only want to send a small message: https://gist.github.com/kibotu/5fb14d617122fdedb122

**Comment by diegoacuna** [comment]
This should be fixed on PR #47 , now it's merged on the master branch.

**Comment by billoneil** [comment]
This has been merged and will be released soon
