### ISSUE TITLE
"Failed to parse response from request"

### ISSUE THREAD

**Issue by mikeRozen** [rschreijer/lutung#57]
I am trying to send my template
 messages().sendTemplate("WelcomeTest", null, message, Boolean.TRUE);
I do receive mail  as expected but on return "Failed to parse response from request". So I cant 100% be sure if the mail passed or not. Can it be fixed? (I also tried to figured/fix why its happened but unfortunately I cant debug your tests they always get skiped when I run  them)
Thanks for help

**Comment by billoneil** [comment]
@mikeRozen sorry for the delay. I just tested this and it seems to be parsing correctly for me. If this is still an issue for you can you try a newer version?

**Comment by mikeRozen** [comment]
Sure I will try asap and update you.

**Comment by mikeRozen** [comment]
Hi @billoneil ,
Sorry I just used the lutung 0.0.7 and I still have the same issue. 
_" Failed to parse response from request 'https://mandrillapp.com/api/1.0/messages/send-template.json'"_
strange...

**Comment by mikeRozen** [comment]
Fixed on 0.0.8
