### ISSUE TITLE
Ability to add CC to the MandrillMessage.

### ISSUE THREAD

**Issue by codelirium** [rschreijer/lutung#60]
Hello,

I am developing an application an I need to include some email addresses to the CC section of the message.

Looking around at the Mandrill API Docs, I only found support for TO and BCC. Is there any workaround to this? If not, are you open to pull requests for such a feature?

Thanks,
codelirium

**Comment by codelirium** [comment]
Ok so is my understanding correct that the CC is part of the TO section but with Recipient type CC?

**Comment by billoneil** [comment]
I believe that is correct

**Comment by rschreijer** [comment]
yes, that should work. Have you tried it?

**Comment by codelirium** [comment]
Yes, worked fine. Thanks. I have got one more question though.

I realized the the mandrill PROD URL is hardcoded in MandrilApi.rootUrl and fetched via MandrillUtil. If lets say I want to change this URL to point to a mock server, is there any way currently available other than reflection?

**Comment by rschreijer** [comment]
See https://github.com/rschreijer/lutung/pull/39
