### ISSUE TITLE
400 Bad request error after couple of days

### ISSUE THREAD

**Issue by RomaLefrancois** [rschreijer/lutung#68]
Since a couple of weeks we are experiencing an issue with the library. After a couple a days of activity, sending email become impossible because of a HTTP 400 error. 

This is the stack trace I have.
`java.lang.Exception: Email has not been sent. Miss use of the sender service : com.microtripit.mandrillapp.lutung.model.MandrillApiError: Unexpected http status in response: 400 (Bad request). Unparsable JSON response = <html><body><h1>400 Bad request</h1>
Your browser sent an invalid request.
</body></html>`

Restarting the server (jetty) solve the issue. 
It's not an issue with the mandrill API because we have over application components sending email through Mandrill API without issue.

**Comment by billoneil** [comment]
Did you find something on your end for this or do you think there is an issue still?

**Comment by RomaLefrancois** [comment]
The issue was coming from a modification that has been done on your initial code. Sorry about that.
