### ISSUE TITLE
Impossible to send a mail via template api ?

### ISSUE THREAD

**Issue by eelwayadmin** [rschreijer/lutung#70]
Hey,

I see the way to create template through your library, but can't find any method to send a mail with an email template name ?
Not implemented yet ? 

Mandrill api reference : /messages/send-template.json

**Comment by billoneil** [comment]
It is part of the messages api.

https://github.com/rschreijer/lutung/blob/master/src/main/java/com/microtripit/mandrillapp/lutung/controller/MandrillMessagesApi.java#L128

https://github.com/rschreijer/lutung/blob/master/src/test/java/com/microtripit/mandrillapp/lutung/controller/MandrillMessagesApiTest.java#L86

**Comment by eelwayadmin** [comment]
Thx a lot.
