### ISSUE TITLE
Deserializing message events from webhook calls

### ISSUE THREAD

**Issue by corey-tock** [rschreijer/lutung#93]
Looking at the [message event JSON spec](https://mandrill.zendesk.com/hc/en-us/articles/205583307-Message-Event-Webhook-format) in the Mandrill docs and wondering, does this library have a model for mandrill message events? It's basically a wrapper around other models of theirs, with some extra metadata. Trying to record message sends using a webhook. Does anyone have prior art of deserializing the event JSON?

**Comment by jnovotny** [comment]
@corey-tock  Did you ever solve this? I'm trying to figure out how to write code to handle a mandrill webhook as well

**Comment by corey-tock** [comment]
I did not. The feature I wanted to use Mandrill webhooks for remains a lower priority to-do, unfortunately, so I stopped investigating for the time being.

**Comment by evstpet** [comment]
Hi folks! I faced with same iisue when I need use inbuond webhooks, I solved in that way:
POJO for message content:
`@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
@Data
public class MandrillMessageContent {
    private Long ts;
    private String _id;
    private String from_email;
    private String from_name;
    private String subject;
    private MandrillMessage.Recipient to;
    private List<String> tags;
    private Map<String, String> headers;
    private String text;
    private String html;
    private List<MandrillMessage.MessageContent> attachments;
}`

Controller example:
`@RestController
@RequestMapping("/")
public class SimpleRestController {

    @PostMapping
    public String post(@RequestParam Map<String, String> body) throws JsonProcessingException {
        System.out.println(new ObjectMapper().readValue(body.get("mandrill_events"), new TypeReference<List<MandrillMessageContent>>(){}));
        return "Hi Mandrill!";
    }
}`

I used Lombok, SB2, Jackson instead of Gson.

**Comment by lc-nyovchev** [comment]
@corey-tock thank you for closing the issue. Keep in mind that this repo is unsupported. There is a slightly more [modern ](https://github.com/dnovitski/lutung) fork with a couple of fixes like:

- http client upgrade
- some CVE fixes in dependencies
- java 8 support

It's also on [maven central](https://search.maven.org/artifact/io.github.dnovitski/lutung/0.0.12/jar).
